---
- hosts: all
  become: true
  tasks:
   - name: install ntp
     apt:
      pkg: ntp
      state: present
     notify:
      - run update
   - name: start ntp service
     service:
      name: ntp
      state: started
      enabled: true
  handlers:
   - name: run update
     apt:
      update_cache: yes
